[package]
name = "rustsat-playground"
version = "0.1.0"
edition = "2024"
resolver = "3"

[dependencies]
rustsat-glucose = { version = "0.7.2", features = [] }
rustsat = { version = "0.7.2", features = [] }
assertables = "9.5.5"
anyhow = "1.0.98"
